version: 0.0
os: linux
runas: ubuntu

files:
  - source: /
    destination: /home/ubuntu/node-express-realworld-example-app
file_exists_behavior: OVERWRITE
    

hooks:
  
  ApplicationStop:
    - location: scripts/stop_script.sh
      timeout: 300
      
 
