version: 0.0
os: linux
runas: aadesh

files:
  - source: /
    destination: /home/ubuntu/node-express-realworld-example-app
    overwrite: true
    timeout: 300

hooks:
  BeforeInstall:
    - location: scripts/install.sh
      timeout: 300
      runas: aadesh
  ApplicationStop:
    - location: scripts/stop_script.sh
      timeout: 300
      runas: aadesh
  ApplicationStart:
    - location: scripts/start_script.sh
      timeout: 300
      runas: aadesh
  ValidateService:
    - location: scripts/validate_service.sh
      timeout: 300
      runas: aadesh
