version: 0.0
os: linux
runas: root

files:
  - source: /
    destination: /home/ubuntu/node-express-realworld-example-app
    overwrite: true
    timeout: 300

hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 300
     
  ApplicationStop:
    - location: scripts/stop_script.sh
      timeout: 300
      
  ApplicationStart:
    - location: scripts/start_script.sh
      timeout: 300
     
  ValidateService:
    - location: scripts/validate_service.sh
      timeout: 300
