version: 0.0
os: linux
runas: ubuntu

files:
  - source: /
    destination: /home/ubuntu/node-express-realworld-example-app
file_exists_behavior: OVERWRITE
    
hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 300
      runas: ubuntu
  ApplicationStop:
    - location: scripts/stop_script.sh
      timeout: 300
      runas: ubuntu
  ApplicationStart:
    - location: scripts/start_script.sh
      timeout: 300
      runas: ubuntu
