version: 0.2

env:
        parameter-store:
                mongo_url: "/aadesh/mongo_url"

phases:
        pre_build:
                commands:
                        - npm install
        build:
                commands:
#                          - sed -i 's|mongodb://localhost/conduit|'$mongo_url'|' app.js
                         - echo "NODE_ENV=production" > .env
                         - echo "MONGODB_URI=$mongo_url" >> .env
                         - echo "PORT=3000" >> .env
                         - echo "SECRET=c494aab3-af14-4797-86cc-78a2307e999f" >> .env
                         - cat .env
                         - ls -al
        post_build:
                commands:
                        - cat app.js
artifacts:
        files:
                - '**/*'
                - echo "Build Artifacts created successfully and uploaded to S3 Bucket"

