version: 0.2

run-as: aadesh

env:
        parameter-store:
                mongo_url: "/aadesh/mongo_url"

phases:
        pre_build:
                commands:
                        - npm install
        build:
                commands:
                        - sed -i 's|mongodb://localhost/conduit|'$mongo_url'|' app.js
        post_build:
                commands:
                        - cat app.js
artifacts:
        files:
                - '**/*'
                - echo "Build Artifacts created successfully and uploaded to S3 Bucket"

